# https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/

---
name: AllStar Enforcement Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: 
      # although AllStar signs their container with co-sign, there's no indication GitHub actions
      # checks Docker signatures, so I'm specifying AllStar by SHA.
      image: ghcr.io/ossf/allstar@sha256:1f3b9d7bf8490f17f1c114781085a92124e187c7e59db53b1e8a996d85c36445 
      options: --user root
    environment: prod
    env:
      ARTIFACT_DIR: /tmp/artifacts
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4
      - name: Verify image
        run: |
          cosign verify ghcr.io/ossf/allstar@sha256:1f3b9d7bf8490f17f1c114781085a92124e187c7e59db53b1e8a996d85c36445 
      - name: Create Artifact Directoy
        run: mkdir $ARTIFACT_DIR 
      - name: Run AllStar Policy Check
        env:
          # Ping open issues every week (168 hours)
          NOTICE_PING_DURATION_HOURS: 168
          DO_NOTHING_ON_OPT_OUT: true # consistent with https://github.com/ossf/allstar/blob/main/app-prod.yaml#L12
          ALLSTAR_LOG_LEVEL: info # use debug when needed.
          KEY_SECRET: direct
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once > >(tee -a $ARTIFACT_DIR/stdout.log) 2> >(tee -a $ARTIFACT_DIR/stderr.log >&2)
      - name: Archive AllStar Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # @4.3.1
        with:
          name: allstar-artifacts
          path: $ARTIFACT_DIR