---
name: AllStar Enforcement Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: ghcr.io/ossf/allstar:v4.0-busybox
    environment: prod
    steps:
    - run: mkdir -p /tmp/artifact
    - run: echo hello > /tmp/artifact/world.txt
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # @4.3.1
      with:
        name: my-artifact
        path: /tmp/artifact/world.txt    
