---
name: AllStar Enforcement Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: ghcr.io/ossf/allstar:v4.0-busybox
    environment: prod
    steps:
      - run: mkdir /home/nonroot/artifacts
      - run: date > /home/nonroot/artifacts/date.out
      - uses: actions/upload-artifact@v4
        with:
          name: allstar-artifacts
          path: /home/nonroot/artifacts/
