---
name: AllStar Enforcement Action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Use chainguard/busybox based image - It has a tail.
    container: 
      image: ghcr.io/ossf/allstar:sha256-1f3b9d7bf8490f17f1c114781085a92124e187c7e59db53b1e8a996d85c36445.sig
      options: --user root
    environment: prod
    steps:
      - name: Create Artifact Directoy
        run: mkdir /tmp/artifacts
      - name: Run AllStar Policy Check
        env:
          # Ping open issues every week (168 hours)
          NOTICE_PING_DURATION_HOURS: 168
          DO_NOTHING_ON_OPT_OUT: true # consistent with https://github.com/ossf/allstar/blob/main/app-prod.yaml#L12
          ALLSTAR_LOG_LEVEL: info # use debug when needed.
          KEY_SECRET: direct
          APP_ID: ${{ vars.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: /ko-app/allstar -once | tee /tmp/artifacts/allstar-report.txt
      - name: Archive AllStar Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # @4.3.1
        with:
          name: allstar-artifacts
          path: /tmp/artifacts/allstar-report.txt