# https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/

---
name: Verify AllStar Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '26 * * * *'

jobs:
  example:
    runs-on: ubuntu-latest
    name: Install Cosign
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'
      - name: Check install!
        run: cosign version